import { MenuBar } from '@/components/MenuBar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="w-full bg-black h-64 flex items-center justify-center">
          <div className="animate-fade-right animate-once animate-ease-linear">
            <Image
              className="animate-spin animate-once animate-duration-1000 animate-ease-in animate-delay-2000 "
              src="/images/pikaso_reimagine_plain-blank-A-red-and-white-spherical-Pokeball-wit.png"
              width={400}
              height={400}
              alt="pokeball"
            />
          </div>
        </header>
        {children}
        <footer></footer>
      </body>
    </html>
  )
}
